---
name: Test Backend & Frontend
description: Runs back-end and front-end tests

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2

    - run: docker-compose pull
      shell: bash

    - name: Install Invoke
      shell: bash
      run: python -m pip install invoke requests flake8

    - name: Install Invoke
      shell: bash
      run: python -m pip install invoke requests flake8


    - name: Run tests
      shell: bash
      run: inv local.test-all

    - name: Archive pytest test results
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: pytest-test-results
        path: backend/results/*.xml

    - name: Archive angular test results
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: react-test-results
        path: frontend/junit.xml
