from rest_framework.serializers import ModelSerializer
from .models import OVMSData


class OVMSSerializer(ModelSerializer):
    class Meta:
        model = OVMSData
        fields = [
            "id",
            "timestamp",
            "operative_state",
            "latitude",
            "longitude",
            "elevation",
            "slope",
            "speed",
            "odometer",
            "batt_temp",
            "ext_temp",
            "power_kw",
            "capacity",
            "vehicle_id",
            "soc",
            "soh",
            "voltage",
            "current",
            "throttle",
            "regen_brake",
            "consumption",
            "range_est",
            "range_ideal",
            "range_full",
            "drivetime",
            "charge_time",
            "footbrake",
            "engine_temp",
            "is_charging",
            "tpms",
            "coulomb",
            "energy",
            "rpm",
            "charger_type",
            "coulomb_rec",
            "drivemode",
            "energy_rec",
            "mass",
            "mec_power",
            "mean_acc",
            "friction_force",
            "net_force",
            "run",
            "mean_speed",
            "freeram",
            "net_signal",
            "tasks",
            "elevation2",
            "charge_current",
            "angle_x",
            "angle_y",
            "AcX",
            "AcY",
            "AcZ",
            "humidity",
            "kwh_km",
            "assist_level",
            "pressure",
            "user_name",
            "user_id",
            "acceleration",
        ]
