# Generated by Django 4.0.3 on 2023-09-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecoparking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="license_plate",
            field=models.CharField(default="aaa111", max_length=255),
            preserve_default=False,
        ),
    ]
