# Generated by Django 4.0.3 on 2023-09-18 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecoparking", "0002_car_license_plate"),
    ]

    operations = [
        migrations.AddField(
            model_name="station",
            name="address",
            field=models.CharField(default="address", max_length=255),
            preserve_default=False,
        ),
    ]
