# Generated by Django 4.0.3 on 2023-09-16 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ecoparking", "0002_car_license_plate"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ecoparking.brand",
                    ),
                ),
            ],
            options={
                "unique_together": {("brand", "name")},
            },
        ),
    ]
