# Generated by Django 4.0.3 on 2023-09-19 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecoparking", "0003_station_address"),
        ("ecoparking", "0004_alter_car_model"),
    ]

    operations = []
