# Generated by Django 4.0.3 on 2023-11-08 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecoparking", "0005_merge_0003_station_address_0004_alter_car_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="appmodel",
            name="range",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
