---
name: Test PR

on:
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  test-frontend-backend:
    name: Test Backend & Frontend
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/test-frontend-backend

  publish-results:
    name: Publish test results
    runs-on: ubuntu-20.04
    permissions: write-all
    needs: [test-frontend-backend]
    if: ${{ always() }}

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: pytest-test-results
          path: pytest-test-results/
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/download-artifact@v3
        with:
          name: react-test-results
          path: react-test-results/
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: EnricoMi/publish-unit-test-result-action/composite@v2.0.0
        with:
          junit_files: |
            pytest-test-results/*.xml
            react-test-results/*.xml
          repo-token: ${{ secrets.GITHUB_TOKEN }}
